### ISSUE TITLE
Wrong coordinate result with doJupiter() or doSaturn() 

### ISSUE THREAD

**Issue by cedricbellec** [DavidArmstrong/SiderealPlanets#3]
Hello , I try to get back to work my broken Meade ETX LS telescope and I'm using your library.
I get the right coordinates with doMoon() and doSun() but not with doJupiter() or doSaturn(), I've checked with Stellarium data
Also I set GMT date and time and observation lat long from GPS data.
Can you help ?

**Comment by DavidArmstrong** [comment]
I'll need more information to be able to track down an error.  The Example7_Planets sketch shows the basics of how to set up the library to give planetary coordinates.  If you could take that sketch, and modify it with your parameters, (i.e. Latitude, Longitude, GMT date, time, etc)  and send it to me, I can then look at what it gives and try to track down what the routines are doing.

**Comment by DavidArmstrong** [comment]
FYI - I use this URL site to check the planetary coordinates; http://cosinekitty.com/solar_system.html

**Comment by cedricbellec** [comment]
Thank you for the link,  it seems to work now  ,it was probably an error in my code.
Regards,
Cédric
