### ISSUE TITLE
very odd anomaly...

### ISSUE THREAD

**Issue by markh1301** [DavidArmstrong/SiderealPlanets#4]
Hello David,
Ive tried the Example4_Sun example on a mega2560 and I get massive errors compared to my iPhone/iPad star app. Also my location and a fair dose of common sense tells me something is up with the code. For example I just set time to 28th Jan 2022 with some approx coords (53 latitude N and 0.6 long W) and it returns Sunrise @ 18.09 and Sunset at 02.52

**Comment by DavidArmstrong** [comment]
I used your reported settings, and modified Example4_Sun as follow:

`/* Sidereal Planets Library - Sun functions
 * Version 1.1.0 - September 1, 2021
 * Example4_Sun
*/

#include <SiderealPlanets.h>

// Need the following define for SAMD processors
#if defined (ARDUINO_ARCH_SAMD)
#define Serial SerialUSB
#endif

SiderealPlanets myAstro;

void setup() {
  Serial.begin(9600);
  delay(2000); //SAMD boards may need a long time to init SerialUSB
  Serial.println("Sidereal Planets Sun Functions");
  myAstro.begin();
  Serial.println("\nBecause these calculations are dependent on both time and location,");
  Serial.println("those values have to be set first.");
  Serial.println("We can use the decimalDegrees() function to make this easier.");
  Serial.println("We define:");
  Serial.println("DST off, time zone = 0");
  Serial.println("GMT date: January 28, 2022  Local Time: 19:00:00");
  myAstro.setTimeZone(0);
  myAstro.rejectDST();
  myAstro.setGMTdate(2022,1,28);
  myAstro.setLocalTime(19,0,0.0);
  
  Serial.println("\nNow calculate the Sun's position:");
  myAstro.doSun();
  Serial.print("Right Ascension = ");
  myAstro.printDegMinSecs(myAstro.getRAdec());
  Serial.println("");
  Serial.print("Declination = ");
  myAstro.printDegMinSecs(myAstro.getDeclinationDec());
  Serial.println();
  Serial.println("\n");
  
  Serial.println("We also calculate Sun Rise/Set times.");
  Serial.println("We set: DST off, time zone = 0");
  Serial.println("Longitude = 0:36:0 = 0.6 W; Latitude = 53:0:0");
  
  myAstro.rejectDST();
  myAstro.setTimeZone(0);
  myAstro.setLatLong(myAstro.decimalDegrees(53,0,0), myAstro.decimalDegrees(0,36,0));
  myAstro.doSunRiseSetTimes();
  Serial.println("\nOur results should be/are:");
  Serial.print("Local SunRise= ");
  myAstro.printDegMinSecs(myAstro.getSunriseTime());
  Serial.println("");
  Serial.print("Local SunSet= ");
  myAstro.printDegMinSecs(myAstro.getSunsetTime());
  Serial.println("");
}

void loop() {
  while(1); //Freeze
}`

The output I get from my Redboard Turbo when I run this is as follows:

`Sidereal Planets Sun Functions

Because these calculations are dependent on both time and location,
those values have to be set first.
We can use the decimalDegrees() function to make this easier.
We define:
DST off, time zone = 0
GMT date: January 28, 2022  Local Time: 19:00:00

Now calculate the Sun's position:
Right Ascension = 20:41:45.85
Declination = -18:15:35.44


We also calculate Sun Rise/Set times.
We set: DST off, time zone = 0
Longitude = 0:36:0 = 0.6 W; Latitude = 53:0:0

Our results should be/are:
Local SunRise= 7:47:19.87
Local SunSet= 16:34:16.02

`
These results look very reasonable to me. 
I do not have a Mega board to test this same code variation.  However the Arduino IDE does compile the source code without errors when I select the Mega as a target processor.

Try my code listing as shown above on your board, and report any differences shown in the output.

Dave

**Comment by markh1301** [comment]
/* Sidereal Planets Library - Sun functions
 * Version 1.1.0 - September 1, 2021
 * Example4_Sun
*/

#include <SiderealPlanets.h>

// Need the following define for SAMD processors
#if defined (ARDUINO_ARCH_SAMD)
#define Serial SerialUSB
#endif

SiderealPlanets myAstro;

void setup() {
  Serial.begin(9600);
delay(2000); //SAMD boards may need a long time to init SerialUSB
Serial.println("Sidereal Planets Sun Functions");
myAstro.begin();
Serial.println("\nBecause these calculations are dependent on both time and location,");
Serial.println("those values have to be set first.");
Serial.println("We can use the decimalDegrees() function to make this easier.");
Serial.println("We define:");
Serial.println("DST off, time zone = 0");
Serial.println("GMT date: January 28, 2022 Local Time: 19:00:00");
myAstro.setTimeZone(0);
myAstro.rejectDST();
myAstro.setGMTdate(2022,1,28);
myAstro.setLocalTime(19,0,0.0);
  
  Serial.println("\nNow calculate the Sun's position:");
myAstro.doSun();
Serial.print("Right Ascension = ");
myAstro.printDegMinSecs(myAstro.getRAdec());
Serial.println("");
Serial.print("Declination = ");
myAstro.printDegMinSecs(myAstro.getDeclinationDec());
Serial.println();
Serial.println("\n");

Serial.println("We also calculate Sun Rise/Set times.");
Serial.println("We set: DST off, time zone = 0");
Serial.println("Longitude = 0:36:0 = 0.6 W; Latitude = 53:0:0");
  
  myAstro.rejectDST();
  myAstro.setTimeZone(0);
  myAstro.setLatLong(myAstro.decimalDegrees(53,0,0), myAstro.decimalDegrees(0,36,0));
  myAstro.doSunRiseSetTimes();
  Serial.println("\nOur results should be/are:");
  Serial.print("Local SunRise= ");
  myAstro.printDegMinSecs(myAstro.getSunriseTime());
  Serial.println("");
  Serial.print("Local SunSet= ");
  myAstro.printDegMinSecs(myAstro.getSunsetTime());
  Serial.println("");
}

void loop() {
  while(1); //Freeze
}

Here is output from both of my Mega2560 this Sunday morning...

Because these calculations are dependent on both time and location,
those values have to be set first.
We can use the decimalDegrees() function to make this easier.
We define:
DST off, time zone = 0
GMT date: January 28, 2022 Local Time: 19:00:00

Now calculate the Sun's position:
Right Ascension = 20:41:45.97
Declination = -18:15:35.00


We also calculate Sun Rise/Set times.
We set: DST off, time zone = 0
Longitude = 0:36:0 = 0.6 W; Latitude = 53:0:0

Our results should be/are:
Local SunRise= 18:8:12.43
Local SunSet= 2:54:44.30


Thanks for getting back David. I don’t have any other type of Arduino that can handle the memory requirements so I cannot help there. The one think I can contribute is that the calculation is not always wrong…
Using all default values on the same Mega2560 straight out of the box example4_Sun….

Because these calculations are dependent on both time and location,
those values have to be set first.
We can use the decimalDegrees() function to make this easier.
We define:
DST off, time zone = -5
GMT date: August 24, 1984  Local Time: 19:00:00

Now calculate the Sun's position:
Right Ascension = 10:12:11.37  ==> 10:12:11.72 
Declination = 11:7:9.01  ==> 11:7:7.14 


We can also calculate Sun Rise/Set times.
We set: DST off, time zone = 0, date: Oct 1, 1984
Longitude = 0:0:0; Latitude = 52:0:0

Our results should be/are:
Local SunRise=6:0:58.12  ==> 6:0:58.36 
Local SunSet=17:37:10.86  ==> 17:37:10.80

**Comment by markh1301** [comment]
Hello David,
Did you find anything odd with the Mega2560 code?
Could it be specific to that device?
Wishing you good luck with your debug!

**Comment by DavidArmstrong** [comment]
Haven't had a millisecond to look at this. Broke my wrist, and typing one-handed is difficult. I'll try to get back to this as soon as I can. It definitely is something related to the mega code segment in the library though.

**Comment by markh1301** [comment]
Oh dear! I’m sorry to hear that! Sounds very painful so get well soon!

**Comment by DavidArmstrong** [comment]
I examined the code again, and see that there are no Mega-specific sections to it.  In other words, the exact same code is being compiled and run on the Mega as on my SAMD board.  It's just a different variation of the GCC complier that is doing the actual compilation. So whatever is messing this up on the Mega is specific to that compiler build.
I do know that a big difference between ARM and Atmel processors is the handling of double vs. float.  Quoting from https://forum.pjrc.com/threads/44011-Teensy-3-2-Maths-compatablity-with-Mega-2560 here:

"On AVR platforms, double is the same as float (i.e. 32-bit floating point). On ARM platforms, double is 64-bits and float is 32-bits."

While this doesn't seem like it should cause a problem as big as seen here, I can't rule it out.  Without the two processors side-by-side to do comparisons, I can't easily find where the Mega GCC is going wildly different, compared to the SAMD GCC implementation.  The best I could do is hork up a special build to print out values when doing the Sunrise/Sunset calculations, and then each of us run that build to compare the outputs, and see where they diverge.

**Comment by DavidArmstrong** [comment]
As a start, I updated this one routine in the SiderealPlanets.cpp file:

boolean SiderealPlanets::doSunRiseSetTimes(void) {
  double horizonVerticalDisplacement = 1.454441e-2;
  double tmpGMT = GMTtime;
  GMTtime = (12.0 + (TimeZoneOffset + DSToffset));
  doSun();
  GMTtime = tmpGMT;
  if (doRiseSetTimes(rad2deg(horizonVerticalDisplacement)) == false) return false;
  
  double LA_local = localSiderealTimeRising; //localSiderealTime of rising - first guesstimate
  Serial.print("LA_local #1 = ");
  Serial.println(LA_local);
  double LB_local = localSiderealTimeSetting; //localSiderealTime of setting - first guesstimate
  Serial.print("LB_local #1 = ");
  Serial.println(LB_local);
  double GU_local = doLST2GMT(LA_local);
  double GD_local = doLST2GMT(LB_local);
  
  GMTtime = GU_local;
  double DN_local = mjd1900;
  double A_local = GMTtime + TimeZoneOffset + DSToffset;
  if (A_local > 24.) mjd1900 -= 1;
  if (A_local < 0.)  mjd1900 += 1;
  Serial.print("mjd1900 #1 = ");
  Serial.println(mjd1900);
  doSun();
  mjd1900 = DN_local;
  GMTtime = tmpGMT;
  if (doRiseSetTimes(rad2deg(horizonVerticalDisplacement)) == false) return false;
  LA_local = localSiderealTimeRising; //AA_local = azimuthRising;
  Serial.print("LA_local #2 = ");
  Serial.println(LA_local);
  
  GMTtime = GD_local;
  A_local = GMTtime + TimeZoneOffset + DSToffset;
  if (A_local > 24.) mjd1900 -= 1;
  if (A_local < 0.)  mjd1900 += 1;
  Serial.print("mjd1900 #2 = ");
  Serial.println(mjd1900);
  doSun();
  mjd1900 = DN_local;
  GMTtime = tmpGMT;
  if (doRiseSetTimes(rad2deg(horizonVerticalDisplacement)) == false) return false;
  
  LB_local = localSiderealTimeSetting; //AB_local = azimuthSetting;
  Serial.print("LB_local #2 = ");
  Serial.println(LB_local);
  localSiderealTimeRising = LA_local;
  return true;
}

My output is as follows, using the exact same test routine as before:

We also calculate Sun Rise/Set times.
We set: DST off, time zone = 0
Longitude = 0:36:0 = 0.6 W; Latitude = 53:0:0
LA_local #1 = 16.34
LB_local #1 = 1.12
mjd1900 #1 = 44587.50
LA_local #2 = 16.33
mjd1900 #2 = 44587.50
LB_local #2 = 1.14

Our results should be/are:
Local SunRise= 7:47:19.87
Local SunSet= 16:34:16.02

If you could update this one routine in your copy of the library, run it on the Mega, and show me the output, that will provide a first pass as to where the problem may lie.

**Comment by markh1301** [comment]
Because these calculations are dependent on both time and location,
those values have to be set first.
We can use the decimalDegrees() function to make this easier.
We define:
DST off, time zone = -5
GMT date: August 24, 1984  Local Time: 19:00:00

Now calculate the Sun's position:
Right Ascension = 10:12:11.37  ==> 10:12:11.72 
Declination = 11:7:9.01  ==> 11:7:7.14 


We can also calculate Sun Rise/Set times.
We set: DST off, time zone = 0, date: Oct 1, 1984
Longitude = 0:0:0; Latitude = 52:0:0
LA_local #1 = 6.72
LB_local #1 = 18.32
mjd1900 #1 = 30954.50
LA_local #2 = 6.69
mjd1900 #2 = 30954.50
LB_local #2 = 18.33

Our results should be/are:
Local SunRise=6:0:58.12  ==> 6:0:58.36 
Local SunSet=17:37:10.86  ==> 17:37:10.80 
Sidereal Planets Sun Functions

Because these calculations are dependent on both time and location,
those values have to be set first.
We can use the decimalDegrees() function to make this easier.
We define:
DST off, time zone = -5
GMT date: January 28, 2022 Local Time: 19:00:00

Now calculate the Sun's position:
Right Ascension = 10:12:11.37  ==> 20:41:45.97 
Declination = 11:7:9.01  ==> -18:15:35.00 


We can also calculate Sun Rise/Set times.
We set: DST off, time zone = 0
Longitude = 0:36:0 = 0.6 W; Latitude = 53:0:0
LA_local #1 = 6.73
LB_local #1 = 18.31
mjd1900 #1 = 30954.50
LA_local #2 = 6.70
mjd1900 #2 = 30954.50
LB_local #2 = 18.32

Our results should be/are:
Local SunRise= 5:59:3.27 
Local SunSet= 17:34:15.33

**Comment by markh1301** [comment]
Sidereal Planets Sun Functions

Because these calculations are dependent on both time and location,
those values have to be set first.
We can use the decimalDegrees() function to make this easier.
We define:
DST off, time zone = 0
GMT date: January 28, 2022 Local Time: 19:00:00

Now calculate the Sun's position:
Right Ascension = 20:41:45.97 
Declination = -18:15:35.00 


We also calculate Sun Rise/Set times.
We set: DST off, time zone = 0
Longitude = 0:36:0 = 0.6 W; Latitude = 53:0:0
LA_local #1 = 16.34
LB_local #1 = 1.12
mjd1900 #1 = 44587.50
LA_local #2 = 16.35
mjd1900 #2 = 44587.50
LB_local #2 = 1.08

Our results should be/are:
Local SunRise= 18:8:12.43 
Local SunSet= 2:54:44.30

**Comment by DavidArmstrong** [comment]
Let's add in another 'instrumented' function to the library:

double SiderealPlanets::doLST2LT(double localSiderealTime) {
  //for computing rise/set times
  modifiedJulianDate1900();
  Serial.print("mjd1900 = ");
  Serial.println(mjd1900);
  double days = ((int)(mjd1900 - 0.5)) + 0.5;
  Serial.print("days = ");
  Serial.println(days);
  double t = (days / 36525.0) - 1.;
  Serial.print("t = ");
  Serial.println(t);
  double r0 = t * (5.13366e-2 + (t * (2.586222e-5 - (t * 1.722e-9))));
  Serial.print("r0 = ");
  Serial.println(r0);
  double r1 = 6.697374558 + (2400.0 * (t - ((GMTyear - 2000.0) / 100.0)));
  
  double t0 = inRange24(r0 + r1);
  Serial.print("t0 = ");
  Serial.println(t0);
  double julianCenturies1900 = inRange24(t0 - (DSToffset + TimeZoneOffset) * 1.002737908);
  Serial.print("julianCenturies1900 = ");
  Serial.println(julianCenturies1900);
  double GSTdecimalhours = inRange24(localSiderealTime - (decLong / 15.0));
  Serial.print("GSTdecimalhours = ");
  Serial.println(GSTdecimalhours);
  if (GSTdecimalhours < julianCenturies1900) GSTdecimalhours += 24.;
  double localTimeDecimalHours = inRange24((GSTdecimalhours - julianCenturies1900) * 9.972695677e-1);
  return localTimeDecimalHours;
}

When I run this, I get this output for the January 28, 2022 date:

We also calculate Sun Rise/Set times.
We set: DST off, time zone = 0
Longitude = 0:36:0 = 0.6 W; Latitude = 53:0:0
LA_local #1 = 16.34
LB_local #1 = 1.12
mjd1900 = 44587.50
days = 44587.50
t = 0.22
r0 = 0.01
t0 = 8.48
julianCenturies1900 = 8.48
GSTdecimalhours = 16.30
mjd1900 = 44587.50
days = 44587.50
t = 0.22
r0 = 0.01
t0 = 8.48
julianCenturies1900 = 8.48
GSTdecimalhours = 1.08
mjd1900 #1 = 44587.50
LA_local #2 = 16.33
mjd1900 #2 = 44587.50
LB_local #2 = 1.14

Our results should be/are:
Local SunRise= mjd1900 = 44587.50
days = 44587.50
t = 0.22
r0 = 0.01
t0 = 8.48
julianCenturies1900 = 8.48
GSTdecimalhours = 16.29
7:47:19.87
Local SunSet= mjd1900 = 44587.50
days = 44587.50
t = 0.22
r0 = 0.01
t0 = 8.48
julianCenturies1900 = 8.48
GSTdecimalhours = 1.10
16:34:16.02

Let's see what the Mega gives us with this.

**Comment by markh1301** [comment]
Sidereal Planets Sun Functions

Because these calculations are dependent on both time and location,
those values have to be set first.
We can use the decimalDegrees() function to make this easier.
We define:
DST off, time zone = 0
GMT date: January 28, 2022 Local Time: 19:00:00

Now calculate the Sun's position:
Right Ascension = 20:41:45.97 
Declination = -18:15:35.00 


We also calculate Sun Rise/Set times.
We set: DST off, time zone = 0
Longitude = 0:36:0 = 0.6 W; Latitude = 53:0:0
LA_local #1 = 16.34
LB_local #1 = 1.12
mjd1900 = 44587.50
days = -20948.50
t = -1.57
r0 = -0.08
t0 = 22.12
julianCenturies1900 = 22.12
GSTdecimalhours = 16.30
mjd1900 = 44587.50
days = -20948.50
t = -1.57
r0 = -0.08
t0 = 22.12
julianCenturies1900 = 22.12
GSTdecimalhours = 1.08
mjd1900 #1 = 44587.50
LA_local #2 = 16.35
mjd1900 #2 = 44587.50
LB_local #2 = 1.08

Our results should be/are:
Local SunRise= mjd1900 = 44587.50
days = -20948.50
t = -1.57
r0 = -0.08
t0 = 22.12
julianCenturies1900 = 22.12
GSTdecimalhours = 16.31
18:8:12.43 
Local SunSet= mjd1900 = 44587.50
days = -20948.50
t = -1.57
r0 = -0.08
t0 = 22.12
julianCenturies1900 = 22.12
GSTdecimalhours = 1.04
2:54:44.30

**Comment by DavidArmstrong** [comment]
I definitely found one issue, which is now fixed in version 1.1.1 of the library.  When the Arduino Library manager updates with the new release, go ahead and test it out to verify if it resolves this issue for you.  (And yes, it is something subtly specific to the Mega processor as compared to the SAMD boards that I use.)

**Comment by markh1301** [comment]
I’m glad I could highlight the issue and you figured out the solution. Thanks for your efforts!

Btw do you use an arduino zero? I wondered if that might be a good debug tool for my baby steps in c coding…and it’s a step up from a mega2560

**Comment by DavidArmstrong** [comment]
Closing issue as it has been untouched in over a year.
